name: CI Pipeline

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install project
        run: pip install -e .

      - name: Run lint
        run: flake8 .

      - name: Run tests
        run: pytest
      ################################################
      # AWS + Docker Section
      ################################################
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::800939196792:role/GitHubDeploymentRole
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-app:latest
          docker build -t $IMAGE_URI .

      - name: Push Docker Image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-app:latest
          docker push $IMAGE_URI
      # ---------------------------
      #   BUILD ARTIFACT
      # ---------------------------
      - name: Build Python Package
        run: |
          python -m build
        # this generates /dist/my-app-0.1.0.tar.gz and .whl

      # ---------------------------
      #   UPLOAD ARTIFACT
      # ---------------------------
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/*
